export default {
  products: [
    {
      _id: 4,
      name: "Slim Shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 10,
    },
    {
      _id: 6,
      name: "Slim Shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
    },
    {
      _id: 3,
      name: "Slim Shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: 2,
      name: "Slim Shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 8,
    },
    {
      _id: 1,
      name: "Slim Shirt",
      image: "/images/d1.jpg",
      price: 60,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 0,
    },
  ],
};
